import { CaseStudyPageLayout } from '../../components/CaseStudyPageLayout';

const caseData = {
  title: 'Dyvo',
  category: 'AI • Creative Tool',
  description: 'An AI-powered application that allows users to create stunning art drawings and avatars from their photos. The app achieved 50K+ downloads and maintains a 4.8-star rating.',
  heroImage: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=1600&h=900&fit=crop',
  color: '#FF8C42',
  client: 'Dyvo Labs',
  timeline: '2.5 months',
  services: ['No-Code Development', 'AI Integration', 'Mobile App Design'],
  
  challenge: 'Dyvo wanted to create a consumer app that would let anyone transform their photos into unique AI-generated artwork. The challenge was to integrate multiple AI models, handle high-volume image processing, and create a seamless user experience—all while keeping costs manageable for a freemium business model.',
  
  solution: [
    {
      title: 'Multi-Model AI Pipeline',
      description: 'Integrated multiple AI models including Stable Diffusion and custom-trained models to offer a variety of art styles. Users can transform photos into anime, oil paintings, watercolors, and more.',
    },
    {
      title: 'Smart Queue System',
      description: 'Built an intelligent processing queue that optimizes AI generation based on user tier, server load, and complexity. Premium users get priority processing while free users still get reasonable wait times.',
    },
    {
      title: 'Gallery & Social Features',
      description: 'Created a community gallery where users can share their creations, like and comment on others\' work, and follow their favorite creators. This viral loop helped drive organic growth.',
    },
    {
      title: 'Monetization System',
      description: 'Implemented a freemium model with in-app purchases for credits, subscriptions for unlimited generations, and special style packs. The system handles payments via Stripe and manages credit balances.',
    },
  ],
  
  techStack: [
    { name: 'Bubble', icon: '🫧' },
    { name: 'Stable Diffusion', icon: '🎨' },
    { name: 'OpenAI', icon: '🤖' },
    { name: 'AWS Lambda', icon: '⚡' },
    { name: 'Cloudflare', icon: '☁️' },
    { name: 'Stripe', icon: '💳' },
    { name: 'Firebase', icon: '🔥' },
    { name: 'RevenueCat', icon: '💰' },
  ],
  
  gallery: [
    { url: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=1200&h=800&fit=crop', caption: 'AI Art Gallery', size: 'large' },
    { url: 'https://images.unsplash.com/photo-1547826039-bfc35e0f1ea8?w=800&h=600&fit=crop', caption: 'Style Selection' },
    { url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&h=600&fit=crop', caption: 'Generated Artwork' },
  ],
  
  results: [
    { value: '50K+', label: 'Downloads', description: 'Total app downloads across platforms' },
    { value: '4.8★', label: 'Rating', description: 'Average user rating on app stores' },
    { value: '2M+', label: 'Images', description: 'AI artworks generated by users' },
    { value: '15%', label: 'Conversion', description: 'Free to paid user conversion rate' },
  ],
  
  testimonial: {
    quote: 'The team at Sommo understood our vision immediately. They not only built what we asked for but suggested features that made the product even better. The AI integration is flawless.',
    author: 'Anna Kowalski',
    role: 'Product Lead, Dyvo',
  },
  
  nextCase: {
    title: 'Curri Logistics',
    href: '/cases/curri',
  },
};

export const DyvoPage = () => {
  return <CaseStudyPageLayout {...caseData} />;
};

